### PR TITLE
Travis CI and Codecov setup for Django-REST-Framework-Mongoengine

### PR DESCRIPTION
**Pull request by BurkovBA**
Hi, mr. Qwiglydee and Umut Bozkurt, many thanks for the work, you're doing, guys!

I created all the necessary files for Travis CI and Codecov configuration for DRF-Mongoengine and made them successfully do their job in my fork: https://github.com/BurkovBA/django-rest-framework-mongoengine (see green badges). The configuration is 99%-rip-off of Django-REST-Framework's with all the necessary modifications. I'll denote the non-trivial changes, I had to introduce:

1. Had to rename `DumbDocument` to `PatchingDumbDocument` in `test_patching.py`. Reason for this is mongoengine's document registry. When you import a Document, it automatically registers itself in mongoengine's regsitry and will be known by its name there. As you have DumbDocument defined both in `tests/models.py` and in `tests/test_patching.py`, they clash in the registry, when pytest autodiscovers them, and `get_document()` function retrieves the wrong document, failing the tests. Thus, I renamed one of them.
2. Python2 support: there were some minor incompatibilities with python2 in DRFM: `super()` can't be invoked without arguments in Python2 and `mock` module isn't a part of unittest in 2.7. For `mock`, I added conditional import, just as it is done in Django.
3. Satisfy linter: there were some unused imports, formatting errors that flake8 cursed about, which I fixed. Also, `isort` was unhappy about the order of some imports; I've written a `.isort.cfg` for it. I also replaced isort's `--check-only` option, which fails the build, if isort is unhappy, with `--diff`, which complains, but doesn't fail.
4. I created a separate requirements folder, just as it is done in DRF. It is used by `tox.ini` to customize build environments.
5. I prepared the stub for Django1.10 testing and documentation build job. Unfortunately, DRFM documentation is not available in the repo, thus, I can't make it work.

You'll probably want your Travis CI and Codecov badges in `README.md` refer to your own Travis and Codecov accounts (currently, they refer to mine, as I had no other way to test them). Just ask Umut to regsiter this repo in Travis and Codecov with his github account.

All in all, your test coverage is very good, over 90%. Cheers!

### CODE REVIEW

**Comment by qwiglydee** [comment]
Thanks for your efforts.
I will check and merge ASAP.

**Comment by BurkovBA** [comment]
Oops, sorry, I mixed my new commits with the Pull request. 

Should I use feature branches like in git flow for my pull requests in future? Or just push to master?

These new commits are a test suit for issue #175: https://github.com/umutbozkurt/django-rest-framework-mongoengine/issues/175. Strangely, this test fails: despite the comment, mongoengine won't automagically create EmbeddedDocuments from nested data in Serializer.create: https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/serializers.py#L148. I don't understand, how `instance = ModelClass(**validated_data)` is supposed to work.

**Comment by qwiglydee** [comment]
The EmbeddedDocumentSerializer had been designed wrong way - the `.validated_data` returned instance of EmbeddedDocument (to simplify putting it into parent document).

The right way is to follow general API of normal `DocumentSerializer`: the `validated_data` should be a dictionary of (parsed and validated) attributes, and an instance of EmbeddedModel should be created/updated during call to `save`/`create`/`update`.
This way allows to use EmbeddedSerializer separately to implement nested or complicated APIs for embedded list items. (see new test_embedded.py::TestEmbeddedIntegration)
This was the matter of my recent changes.

As for your issue #175 you probably need to take TestCase from `test_dumb.py::TestIntegration`.
And, keep in mind the difference between `serializer.data` and `serializer.validated_data`:
`data` is dictionary of serialized primitive types, ready to be jsonified;
`validated_data` is dictionary of parsed attribute values, ready to be passed to Model constructor.
Thus, ModelClass(**validated_data) creates unsaved instance of an object. Saving an instance is skipped for EmbeddedDocs.

**Comment by BurkovBA** [comment]
@qwiglydee Thanks for the details. So, after sitting in the debugger for quite a while, I came to conclusion that, in fact, the test is correct, but it's DRF-Mongoengine's functioning is wrong - it just relies on DRF's `to_internal_value()` for `DynamicDocumentSerializer` and `DocumentSerializer`: in `validated_data` the value, corresponding to `EmbeddedDocumentSerializer`, is an `OrderedDict`, instead of the expected Mongoengine's `EmbeddedDocument`.

**Comment by qwiglydee** [comment]
In recent changes in master the EmbDocSerizlizer should indeed produce OrdeeredDict in `validated_data`, and an instance in `save`.
It is tested in `TestEmbeddedIntegration` and `TestEmbeddingIntegration`.

But there is no tests on validated_data itself for `EmdDocSerializer` and to_internal value for `EmbDocField` and `EmbDocListField`.
This should go at `TestEmbeddedIntegration.test_parse`, `TestEmbeddingIntegration.test_parse` and new `TestEmbDocField` 
I'm going to fix that stuff ASAP (probably tomorrow or at monday). You are welcome with patches if you working on it right now.

Also, DynamicDocument is probably wrong with `to_internal_value`. And it also need to test_parse.

Also, the master is not intended to be a ready-to-use release, it is indeed just a head of developing.
This is what those badges will show cleanly. 
But I'm not sure how those badges work - are they generated separately for each and every commit or only for heads?

**Comment by BurkovBA** [comment]
@qwiglydee Got it. Besides, so far `EmbeddedDocumentSerializer` does produce `OrderedDict` in `validated_data`. It converts them into a mongoengine object in `update()`, calling `to_instance_value()`. So, I take it, redesign is already underway.

As for the badges, they reflect the state of testes for current head. Travis-CI tests all the configurations, specified in .travis.ci job matrix and if any of them is failing, it says that build is failing. I'm not sure about how Codecov works. It gets coverage report from successful travis tasks and analyzes it. If some tasks don't generate the report (such as `py27-pylint`), badge still generates percentage statistics.

**Comment by qwiglydee** [comment]
ok

**Pull request merged**
