### PR TITLE
Drf 3.1.0 updates

### PR DESCRIPTION
**Pull request by tweiand-10m2**
Updates to allow use with DRF-3.1.0. This patch is not backwards compatible. Also, these look like the minimal changes needed. But, I do not know if I took the best approach on get_fields() in serializer.py.

Will comment my code in this pull request.

Thanks!
-Timothy

### CODE REVIEW

**Comment by tweiand-10m2** [comment]
Passes all my unit and live tests.

**Comment by iorlas** [comment]
Include my commit too, please. See tweiand-10m2/django-rest-framework-mongoengine#1

**Comment by malderete** [comment]
Why the project is not reviewing the PR? This particular one seem ok to me and fixed #110 Thanks!

**Comment by iorlas** [comment]
@malderete because it is a bit... stale now. Many bugs and PRs are here, but nothing happens. I think @umutbozkurt don't have a time to maintain this project anymore.

**Comment by Jcbobo88** [comment]
i'm making test on this pull request, in order to merge it inside the repository, let me some times to complete my tests.

**Comment by Jcbobo88** [comment]
my tests go well, i will merge the pull request.

**Pull request merged**
