### PR TITLE
Fixed broken link to http://mongoengine.org/

### PR DESCRIPTION
**Pull request by dm-wyncode**
modified:   README.md

### CODE REVIEW

**Comment by BurkovBA** [comment]
Hi, Don! Thanks for fixing the link and for your interest! Please, don't use the package from pip as it is currently broken. Instead, load the latest version directly from github: `pip install git+https://github.com/umutbozkurt/django-rest-framework-mongoengine.git`. Either me or Maxim (@qwiglydee) will fix the failing unit-test soon.

**Comment by dm-wyncode** [comment]
Hi, Boris. Thanks. I am new to MongoDB. I look forward to trying it with Django.

**Comment by BurkovBA** [comment]
Do you need a brief primer of how to use DRF-Mongonengine? I'm writing a post at medium.com about how to use it.

I'm currently using DRF-Mongonengine in combination with Postgres, which is used to store users. (Although, if you want to use DRF's authentication, you can easily migrate to Postgres).

Basically, you need to set up a connection with Mongo database in `settings.py`, you need to create a DRF-Mongoengine router to serve your viewsets and for each view you need to create a triplet (document-serialzier-view).

Connection with database can be established in different ways, depending on which version of Mongoengine you're using. If it's `mongoengine<10` (probably, 0.8.7 or 0.9), than it relies on `pymongo==2`, so you can say: 

```
        mongoengine.connect(
            db=MONGODB_DATABASES['default']['TEST']['name'],
            host=MONGODB_DATABASES['default']['host']
        )
```

Than in `urls.py` you create a router like this:
```
from rest_framework_mongoengine.routers import DefaultRouter
router = DefaultRouter()
router.register(r'tool', ToolViewSet, r"tool")
```
 
And you define your model-serializer-view triplets as follows:

```
from mongoengine import Document
from rest_framework_mongoengine.serializers import DocumentSerializer
from rest_framework_mongoengine.viewsets import ModelViewSet

class Tool(Document):
    label = mf.StringField(required=True)
    description = mf.StringField(required=True, null=True)

class ToolSerializer(DocumentSerializer):
    class Meta:
        model = Tool

class ToolViewSet(ModelViewSet):
    lookup_field =  'id'
    serializer_class = ToolSerializer

    def get_queryset(self):
        return Tool.objects.all()
```

Feel free to ask me in [gitter](https://gitter.im/BurkovBA/django-rest-framework-mongoengine), if you need help.

**Comment by dm-wyncode** [comment]
Thank you for this! Very useful. I am working on something else at the
moment. I look forward to checking out django and mongo together.

Thanks for the gitter invite, too. It is new to me.

Don

**Comment by BurkovBA** [comment]
Glad, it helped, Don.

Besides, thanks to your interest I finished the post at Medium about
DRF-Mongoengine
<https://medium.com/@vasjaforutube/django-mongodb-django-rest-framework-mongoengine-ee4eb5857b9a#.sz5jote3e>
.

Good luck with your work.

2016-09-23 1:28 GMT+03:00 Don Morehouse <notifications@github.com>:

**Pull request merged**
